[package]
name = "adventofcode2018"
version = "0.1.0"
authors = ["Koleman Nix <kolemannix@gmail.com>"]
edition = "2018"

[dependencies]
regex = "1"
lazy_static = "1.2.0"
chrono = "0.4"
time = "0.1.41"